# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0042_auto_20180604_1240'),
        ('laborem', '0003_add_device_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedLaboremMotherboardVariable',
            fields=[
            ],
            options={
                'verbose_name': 'Laborem Motherboard Variable',
                'proxy': True,
                'verbose_name_plural': 'Laborem Motherboard Variables',
                'indexes': [],
            },
            bases=('pyscada.variable',),
        ),
    ]
