# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0004_extendedlaboremmotherboardvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pinA',
            field=models.OneToOneField(blank=True, help_text='Relay', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pinA', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pinB',
            field=models.OneToOneField(blank=True, help_text='A0 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pinB', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pinC',
            field=models.OneToOneField(blank=True, help_text='A1 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pinC', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pinD',
            field=models.OneToOneField(blank=True, help_text='A2 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pinD', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pinE',
            field=models.OneToOneField(blank=True, help_text='A3 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pinE', to='gpio.GPIOVariable'),
        ),
    ]
