# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0043_devicewritetask_property_name'),
        ('visa', '0007_auto_20171219_1327'),
        ('laborem', '0005_auto_20180621_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboremRobotElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', null=True, verbose_name='Description')),
                ('value', models.FloatField(default=0)),
                ('active', models.PositiveSmallIntegerField(default=0)),
                ('R', models.FloatField(default=0)),
                ('theta', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.VISADevice')),
                ('unit', models.ForeignKey(on_delete=models.SET(1), to='pyscada.Unit')),
            ],
        ),
    ]
