# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0006_laboremrobotelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboremRobotBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', null=True, verbose_name='Description')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremRobotElement')),
            ],
        ),
    ]
