# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0007_laboremrobotbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboremmotherboardvariable',
            name='laboremmotherboard_variable',
        ),
        migrations.DeleteModel(
            name='ExtendedLaboremMotherboardVariable',
        ),
        migrations.AddField(
            model_name='laboremmotherboarddevice',
            name='plug',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default=0, max_length=254),
        ),
        migrations.DeleteModel(
            name='LaboremMotherboardVariable',
        ),
    ]
