# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0008_auto_20180703_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='MotherboardIOConfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremMotherboardIOConfig'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug1', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug10', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug11', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug12', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug13', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug14', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug15', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug16', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug2', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug3', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug4', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug5', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug6', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug7', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug8', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_plug9', to='laborem.LaboremPlugDevice'),
        ),
    ]
