# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0009_auto_20180709_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremrobotbase',
            name='R',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laboremrobotbase',
            name='theta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laboremrobotbase',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
