# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0002_add_device_protocol'),
        ('laborem', '0010_auto_20180711_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='C0',
        ),
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='V0',
        ),
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='pinA',
        ),
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='pinB',
        ),
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='pinC',
        ),
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='pinD',
        ),
        migrations.RemoveField(
            model_name='laboremmotherboardioconfig',
            name='pinE',
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='C8',
            field=models.ForeignKey(blank=True, help_text='C8 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C8', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='V4',
            field=models.ForeignKey(blank=True, help_text='V4 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_V4', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='pin1',
            field=models.OneToOneField(blank=True, help_text='A0 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pin1', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='pin2',
            field=models.OneToOneField(blank=True, help_text='A1 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pin2', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='pin3',
            field=models.OneToOneField(blank=True, help_text='A2 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pin3', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='pin4',
            field=models.OneToOneField(blank=True, help_text='A3 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pin4', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='pin5',
            field=models.OneToOneField(blank=True, help_text='Relay', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pin5', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='pin6',
            field=models.OneToOneField(blank=True, help_text='Ground', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_pin6', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C1',
            field=models.ForeignKey(blank=True, help_text='C1 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C1', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C2',
            field=models.ForeignKey(blank=True, help_text='C2 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C2', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C3',
            field=models.ForeignKey(blank=True, help_text='C3 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C3', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C4',
            field=models.ForeignKey(blank=True, help_text='C4 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C4', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C5',
            field=models.ForeignKey(blank=True, help_text='C5 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C5', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C6',
            field=models.ForeignKey(blank=True, help_text='C6 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C6', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C7',
            field=models.ForeignKey(blank=True, help_text='C7 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_C7', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V1',
            field=models.ForeignKey(blank=True, help_text='V1 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_V1', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V2',
            field=models.ForeignKey(blank=True, help_text='V2 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_V2', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V3',
            field=models.ForeignKey(blank=True, help_text='V3 connector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobo_V3', to='laborem.LaboremMotherboardIOElement'),
        ),
    ]
