# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laborem', '0013_laboremtop10'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboremTOP10Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='laboremtop10',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laboremtop10score',
            name='TOP10QA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremTOP10'),
        ),
        migrations.AddField(
            model_name='laboremtop10score',
            name='plug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremPlugDevice'),
        ),
        migrations.AddField(
            model_name='laboremtop10score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
