# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('pyscada', '0047_variableproperty_unit'),
        ('laborem', '0016_laboremtop10ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboremGroupInputPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_robot', models.BooleanField(default=False)),
                ('top10_answer', models.BooleanField(default=False)),
                ('hmi_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('laborem_motherboard_device', models.ManyToManyField(blank=True, to='laborem.LaboremMotherboardDevice')),
                ('variable_properties', models.ManyToManyField(blank=True, to='pyscada.VariableProperty')),
                ('variables', models.ManyToManyField(blank=True, to='pyscada.Variable')),
            ],
        ),
    ]
