# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-26 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laborem', '0017_laboremgroupinputpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboremUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('laborem_group_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremGroupInputPermission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
