# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0021_auto_20181026_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremuser',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
