# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0022_laboremuser_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboremuser',
            name='laborem_group_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremGroupInputPermission'),
        ),
    ]
