# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0017_groupdisplaypermission_forms'),
        ('laborem', '0023_auto_20181105_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboremtop10score',
            name='plug',
        ),
        migrations.AddField(
            model_name='laboremtop10',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmi.Page'),
        ),
    ]
