# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0024_auto_20181120_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremtop10score',
            name='answer1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboremtop10score',
            name='answer2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboremtop10score',
            name='answer3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboremtop10score',
            name='answer4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
