# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0026_laboremplugdevice_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremuser',
            name='connection_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laboremplugdevice',
            name='level',
            field=models.CharField(choices=[('1', 'beginner'), ('2', 'intermediate'), ('3', 'advanced')], max_length=254),
        ),
    ]
