# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0021_auto_20190528_0924'),
        ('laborem', '0029_auto_20190924_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboremexperience',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laboremexperience',
            name='short_name',
        ),
        migrations.AddField(
            model_name='laboremexperience',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hmi.Page'),
        ),
    ]
