# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0056_auto_20190625_1823'),
        ('laborem', '0030_auto_20190925_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='mdo2',
            field=models.ForeignKey(blank=True, help_text='Oscilloscope', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc2', to='pyscada.Device'),
        ),
    ]
