# Generated by Django 2.2.6 on 2019-11-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0033_auto_20191107_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='MotherboardIOConfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laborem.LaboremMotherboardIOConfig'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C1',
            field=models.ForeignKey(blank=True, help_text='C1 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C1', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C2',
            field=models.ForeignKey(blank=True, help_text='C2 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C2', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C3',
            field=models.ForeignKey(blank=True, help_text='C3 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C3', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C4',
            field=models.ForeignKey(blank=True, help_text='C4 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C4', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C5',
            field=models.ForeignKey(blank=True, help_text='C5 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C5', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C6',
            field=models.ForeignKey(blank=True, help_text='C6 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C6', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C7',
            field=models.ForeignKey(blank=True, help_text='C7 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C7', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C8',
            field=models.ForeignKey(blank=True, help_text='C8 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_C8', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V1',
            field=models.ForeignKey(blank=True, help_text='V1 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_V1', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V2',
            field=models.ForeignKey(blank=True, help_text='V2 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_V2', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V3',
            field=models.ForeignKey(blank=True, help_text='V3 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_V3', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V4',
            field=models.ForeignKey(blank=True, help_text='V4 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_V4', to='laborem.LaboremMotherboardIOElement'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug1', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug10', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug11', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug12', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug13', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug14', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug15', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug16', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug2', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug3', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug4', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug5', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug6', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug7', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug8', to='laborem.LaboremPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='plug9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_plug9', to='laborem.LaboremPlugDevice'),
        ),
    ]
