# Generated by Django 2.2.8 on 2020-11-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0003_auto_20200211_1721'),
        ('laborem', '0035_auto_20200526_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='switch1',
            field=models.OneToOneField(blank=True, help_text='Switch 1 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch1', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='switch2',
            field=models.OneToOneField(blank=True, help_text='Switch 2 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch2', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='switch3',
            field=models.OneToOneField(blank=True, help_text='Switch 3 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch3', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremmotherboardioconfig',
            name='switch4',
            field=models.OneToOneField(blank=True, help_text='Switch 4 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch4', to='gpio.GPIOVariable'),
        ),
        migrations.AddField(
            model_name='laboremplugdevice',
            name='switch1_value',
            field=models.BooleanField(default=False, help_text='If the PCB host various circuits enter the switches logic to select this circuit. The switches GPIO Pin can be selected in the IO config'),
        ),
        migrations.AddField(
            model_name='laboremplugdevice',
            name='switch2_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laboremplugdevice',
            name='switch3_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laboremplugdevice',
            name='switch4_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C1',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C1 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C2',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C2 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C3',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C3 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C4',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C4 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C5',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C5 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C6',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C6 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C7',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C7 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C8',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='C8 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V1',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='V1 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V2',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='V2 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V3',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='V3 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V4',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'switch1'), ('2', 'switch2'), ('3', 'switch3'), ('4', 'switch4'), ('10', 'MDO1'), ('11', 'MDO2'), ('12', 'MDO3'), ('13', 'MDO4'), ('20', 'AFG1'), ('21', 'AFG2'), ('30', 'DMM_High'), ('31', 'DMM_Low'), ('30', 'DC1'), ('31', 'DC2')], default=0, help_text='V4 connector'),
        ),
    ]
