# Generated by Django 2.2.8 on 2020-11-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0037_auto_20201119_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboremplugdevice',
            name='switch1_value',
        ),
        migrations.RemoveField(
            model_name='laboremplugdevice',
            name='switch2_value',
        ),
        migrations.RemoveField(
            model_name='laboremplugdevice',
            name='switch3_value',
        ),
        migrations.RemoveField(
            model_name='laboremplugdevice',
            name='switch4_value',
        ),
        migrations.CreateModel(
            name='LaboremSubPlugDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default='', max_length=255)),
                ('switch1_value', models.BooleanField(default=False, help_text='If the PCB host various circuits enter the switches logic to select this circuit. The switches GPIO Pin can be selected in the IO config')),
                ('switch2_value', models.BooleanField(default=False)),
                ('switch3_value', models.BooleanField(default=False)),
                ('switch4_value', models.BooleanField(default=False)),
                ('master_plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laborem.LaboremPlugDevice')),
            ],
        ),
    ]
