# Generated by Django 2.2.8 on 2020-11-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0039_laboremsubplugdevice_sub_plug_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboremtop10',
            name='sub_plug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laborem.LaboremSubPlugDevice'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboarddevice',
            name='plug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laborem.LaboremPlugDevice'),
        ),
    ]
