# Generated by Django 2.2.8 on 2020-12-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborem', '0041_auto_20201130_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C1',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C1 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C2',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C2 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C3',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C3 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C4',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C4 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C5',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C5 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C6',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C6 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C7',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C7 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='C8',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='C8 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V1',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='V1 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V2',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='V2 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V3',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='V3 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='V4',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'switch1'), (2, 'switch2'), (3, 'switch3'), (4, 'switch4'), (10, 'MDO1'), (11, 'MDO2'), (12, 'MDO3'), (13, 'MDO4'), (20, 'AFG1'), (21, 'AFG2'), (30, 'DMM_High'), (31, 'DMM_Low'), (40, 'DC1'), (41, 'DC2'), (50, 'Robot Vert'), (51, 'Robot Rouge')], default=0, help_text='V4 connector'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pin1',
            field=models.ForeignKey(blank=True, help_text='A0 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_pin1', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pin2',
            field=models.ForeignKey(blank=True, help_text='A1 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_pin2', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pin3',
            field=models.ForeignKey(blank=True, help_text='A2 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_pin3', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pin4',
            field=models.ForeignKey(blank=True, help_text='A3 connector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_pin4', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pin5',
            field=models.ForeignKey(blank=True, help_text='Relay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_pin5', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='pin6',
            field=models.ForeignKey(blank=True, help_text='Ground', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobo_pin6', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='switch1',
            field=models.ForeignKey(blank=True, help_text='Switch 1 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch1', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='switch2',
            field=models.ForeignKey(blank=True, help_text='Switch 2 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch2', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='switch3',
            field=models.ForeignKey(blank=True, help_text='Switch 3 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch3', to='gpio.GPIOVariable'),
        ),
        migrations.AlterField(
            model_name='laboremmotherboardioconfig',
            name='switch4',
            field=models.ForeignKey(blank=True, help_text='Switch 4 GPIO pin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch4', to='gpio.GPIOVariable'),
        ),
    ]
