alias plog='function _plog(){ if [ $# -eq 1 ]; then tail -fn$1 /var/log/pyscada_debug.log; else tail -fn100 /var/log/pyscada_debug.log;fi };_plog'
alias syslog='function _syslog(){ if [ $# -eq 1 ]; then sudo tail -fn$1 /var/log/syslog; else sudo tail -fn100 /var/log/syslog;fi };_syslog'
alias ll='ls -lah'

alias prestart='function _prestart(){ if [ $# -eq 1 ]; then sudo systemctl restart pyscada_$1; else full_path=$( pwd ); cd /etc/systemd/system/; for i in `sudo ls pyscada*`; do $( sudo systemctl restart $i >/dev/null & ) ; done; cd $full_path;fi };_prestart'
alias grestart='function _grestart(){ if [ $# -eq 1 ]; then sudo systemctl restart gunicorn_$1; else full_path=$( pwd ); cd /etc/systemd/system/; for i in `sudo ls gunicorn*`; do $( sudo systemctl restart $i >/dev/null & ) ; done; cd $full_path;fi };_grestart'
alias pgrestart='function _pgrestart(){ if [ $# -eq 1 ]; then prestart $1; grestart $1; else prestart; grestart; fi };_pgrestart'

alias pstop='function _pstop(){ if [ $# -eq 1 ]; then sudo systemctl stop pyscada_$1; else full_path=$( pwd ); cd /etc/systemd/system/; for i in `sudo ls pyscada*`; do $( sudo systemctl stop $i >/dev/null & ) ; done; cd $full_path;fi };_pstop'
alias gstop='function _gstop(){ if [ $# -eq 1 ]; then sudo systemctl stop gunicorn_$1.service gunicorn_$1.socket; else full_path=$( pwd ); cd /etc/systemd/system/; for i in `sudo ls gunicorn*`; do $( sudo systemctl stop $i >/dev/null & ) ; done; cd $full_path;fi };_gstop'
alias pgstop='function _pgstop(){ if [ $# -eq 1 ]; then gstop $1; pstop $1; else pstop; gstop; fi };_pgstop'

alias pstatus='function _pstatus(){ if [ $# -eq 1 ]; then sudo systemctl status pyscada_$1; else full_path=$( pwd ); cd /etc/systemd/system/; for i in `sudo ls pyscada*`; do $( sudo systemctl status $i >/dev/null & ) ; done; cd $full_path;fi };_pstatus'
alias gstatus='function _gstatus(){ if [ $# -eq 1 ]; then sudo systemctl status gunicorn_$1.service; else full_path=$( pwd ); cd /etc/systemd/system/; for i in `sudo ls gunicorn*service`; do $( sudo systemctl status $i >/dev/null & ) ; done; cd $full_path;fi };_gstatus'
alias pgstatus='function _pgstatus(){ if [ $# -eq 1 ]; then gstatus $1; pstatus $1; else pstatus; gstatus; fi };_pgstatus'

alias psettings='function _psettings(){ if [ $# -eq 1 ]; then sudo -u pyscada nano /var/www/pyscada/PyScadaServer_$1/PyScadaServer_$1/settings.py; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo -u pyscada nano /var/www/pyscada/$i/$i/settings.py"; $cmd ; done; cd $full_path;fi };_psettings'
alias purls='function _purls(){ if [ $# -eq 1 ]; then sudo -u pyscada nano /var/www/pyscada/PyScadaServer_$1/PyScadaServer_$1/urls.py; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo -u pyscada nano /var/www/pyscada/$i/$i/urls.py"; $cmd ; done; cd $full_path;fi };_purls'
alias pstatic='function _pstatic(){ if [ $# -eq 1 ]; then sudo -u pyscada python3 /var/www/pyscada/PyScadaServer_$1/manage.py collectstatic --no-input; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo -u pyscada /usr/bin/python3 /var/www/pyscada/$i/manage.py collectstatic --no-input"; $cmd ; done; cd $full_path;fi };_pstatic'
alias pshell='function _pshell(){ if [ $# -eq 1 ]; then sudo -u pyscada python3 /var/www/pyscada/PyScadaServer_$1/manage.py shell; else sudo -u pyscada python3 /var/www/pyscada/PyScadaServer/manage.py shell;fi };_pshell'
alias pmakemigrations='function _pmakemigrations(){ if [ $# -eq 1 ]; then sudo python3 /var/www/pyscada/PyScadaServer_$1/manage.py makemigrations; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo /usr/bin/python3 /var/www/pyscada/$i/manage.py makemigrations"; $cmd ; done; cd $full_path;fi };_pmakemigrations'
alias pshowmigrations='function _pshowmigrations(){ if [ $# -eq 1 ]; then sudo -u pyscada python3 /var/www/pyscada/PyScadaServer_$1/manage.py showmigrations; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo -u pyscada /usr/bin/python3 /var/www/pyscada/$i/manage.py showmigrations"; $cmd ; done; cd $full_path;fi };_pshowmigrations'
alias pinit='function _pinit(){ if [ $# -eq 1 ]; then sudo -u pyscada python3 /var/www/pyscada/PyScadaServer_$1/manage.py pyscada_daemon init; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo -u pyscada /usr/bin/python3 /var/www/pyscada/$i/manage.py pyscada_daemon init"; $cmd ; done; cd $full_path;fi };_pinit'
alias pmigrate='function _pmigrate(){ if [ $# -eq 1 ]; then sudo -u pyscada python3 /var/www/pyscada/PyScadaServer_$1/manage.py migrate; else full_path=$( pwd ); cd /var/www/pyscada/; for i in `sudo ls -d PyScadaServer*`; do echo $i; cmd="sudo -u pyscada /usr/bin/python3 /var/www/pyscada/$i/manage.py migrate"; $cmd ; done; cd $full_path;fi };_pmigrate'
